#!/bin/bash -l
# Dummy script generated by esm-tools, to be removed later: 
set -e
module purge
module load python3/2023.01-gcc-11.2.0
module load git/2.31.1-gcc-11.2.0
module load cdo/2.0.5-gcc-11.2.0
module load nco/5.0.6-gcc-11.2.0
module load libaec/1.0.5-intel-2021.5.0
module load intel-oneapi-compilers/2022.0.1-gcc-11.2.0
module load intel-oneapi-mkl/2022.0.1-gcc-11.2.0
module load openmpi/4.1.2-intel-2021.5.0
module unload cdo
module load fftw/3.3.10-gcc-11.2.0
module load hdf5/1.12.1-openmpi-4.1.2-intel-2021.5.0
module load netcdf-c/4.8.1-openmpi-4.1.2-intel-2021.5.0
module load netcdf-fortran/4.5.3-openmpi-4.1.2-intel-2021.5.0

export LC_ALL=en_US.UTF-8
export CPU_MODEL=AMD_EPYC_ZEN3
export FESOM_PLATFORM_STRATEGY=levante.dkrz.de
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi2.so
export I_MPI_PMI=pmi2
export FI_PROVIDER=mlx
export I_MPI_OFI_PROVIDER=mlx
export I_MPI_FABRICS=shm:ofi
export HCOLL_ENABLE_MCAST_ALL=1
export HCOLL_MAIN_IB=mlx5_0:1
export UCX_IB_ADDR_TYPE=ib_global
export UCX_NET_DEVICES=mlx5_0:1
export UCX_TLS=mm,knem,cma,dc_mlx5,dc_x,self
export UCX_UNIFIED_MODE=y
export KMP_LIBRARY=turnaround
export KMP_AFFINITY=granularity=fine,scatter
export AEC_ROOT=/sw/spack-levante/libaec-1.0.5-gij7yv
export aec_ROOT=/sw/spack-levante/libaec-1.0.5-gij7yv
export TBBROOT=/sw/spack-levante/intel-oneapi-compilers-2022.0.1-an2cbq/tbb/2021.5.0
export TBBMALLOC_DIR=$TBBROOT/lib/intel64/gcc4.8
export FC=mpif90
export F77=mpif90
export MPICC=mpicc
export MPIFC=mpif90
export CC=mpicc
export CXX=mpicxx
export MPIROOT="$(mpif90 -show | perl -lne 'm{ -I(.*?)/include } and print $1')"
export MPI_LIB="$(mpif90 -show |sed -e 's/^[^ ]*//' -e 's/-[I][^ ]*//g')"
export MPI_HOME=$MPIROOT
export MPI_ROOT=$MPIROOT
export mpi_ROOT=$MPIROOT
export MPI_DIR=$MPIROOT
export mpi_DIR=$MPIROOT
export OMPI_MCA_io=romio321
export LD_RUN_PATH=/sw/spack-levante/netcdf-fortran-4.5.3-k6xq5g/lib:/sw/spack-levante/gcc-11.2.0-bcn7mb/lib64:$LD_LIBRARY_PATH
export UCXROOT=/sw/spack-levante/ucx-1.12.0-nlas56
export HDF5ROOT=/sw/spack-levante/hdf5-1.12.1-tvymb5
export HDF5_C_INCLUDE_DIRECTORIES=$HDF5ROOT/include
export HDF5_ROOT=/sw/spack-levante/hdf5-1.12.1-tvymb5
export NetCDF_C_ROOT=/sw/spack-levante/netcdf-c-4.8.1-2k3cmu
export NetCDF_Fortran_ROOT=/sw/spack-levante/netcdf-fortran-4.5.3-k6xq5g
export NETCDF_PATH=$NetCDF_C_ROOT
export NETCDF_ROOT=$NetCDF_Fortran_ROOT
export NETCDFROOT=$NetCDF_C_ROOT
export NETCDFFROOT=$NetCDF_Fortran_ROOT
export NETCDF_Fortran_INCLUDE_DIRECTORIES=$NETCDFFROOT/include
export NETCDF_C_INCLUDE_DIRECTORIES=$NETCDFROOT/include
export NETCDF_CXX_INCLUDE_DIRECTORIES=$NETCDFROOT/include
export NETCDF_CXX_LIBRARIES=$NETCDFROOT/lib
export LD_LIBRARY_PATH=$MPI_HOME/lib:$NetCDF_C_ROOT/lib:$NetCDF_Fortran_ROOT/lib:$HDF5ROOT/lib:$AEC_ROOT/lib:$UCXROOT/lib:$TBBMALLOC_DIR:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/sw/spack-levante/intel-oneapi-mkl-2022.0.1-ttdktf/mkl/2022.0.1/lib/intel64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/sw/spack-levante/intel-oneapi-mpi-2021.5.0-mrcss7/mpi/2021.5.0/libfabric/lib:$LD_LIBRARY_PATH
export OASIS_NETCDF=$NETCDFROOT
export OASIS_NETCDFF=$NETCDFFROOT
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/on/a/road/to/nowwhere/test/run_20000101-20001231/work//lib/fesom/
export OASIS_FFLAGS="-fPIC"
export OASIS_CFLAGS="-fPIC"
export CFLAGS="-fPIC"
export CCFLAGS="-fPIC"
export FFLAGS="-fPIC"
export FCFLAGS="-fPIC"
export DATA=/on/a/road/to/nowwhere/test/run_20000101-20001231/work/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/on/a/road/to/nowwhere/test/run_20000101-20001231/work//lib/oifs/
export GRIB_SAMPLES_PATH=/work/ab0246/a270092/model_codes/awiesm3-develop/oifs-48r1/build/share/eccodes/ifs_samples/grib1_mlgrib2
export OIFS_LOGFILE=/work/ab0246/a270092/model_codes/awiesm3-develop/oifs-48r1/build/oifs_test_log.txt
export DR_HOOK_IGNORE_SIGNALS=-1
export OIFS_DATA_DIR=/p/project/chhb19/streffing1/input/oifs-48r1/
export C_BLOSC_ROOT=/sw/spack-levante/c-blosc-1.21.6-k4kqv3
export OMP_SCHEDULE=STATIC
export OMP_STACKSIZE=512M
export MKL_NUM_THREADS=1
export MKL_DYNAMIC=FALSE
export I_MPI_ADJUST_ALLREDUCE=3
export I_MPI_ADJUST_BCAST=1
export I_MPI_DEBUG=0
export RNF_OASIS_BASE=$(pwd)/oasis
export RNF_OASIS_INCLUDE="-I$RNF_OASIS_BASE/build/lib/psmile -I$RNF_OASIS_BASE/build/lib/psmile/scrip -I$RNF_OASIS_BASE/build/lib/psmile/mct -I$RNF_OASIS_BASE/build/lib/psmile/mct/mpeu"
export RNF_OASIS_LIB="-L$RNF_OASIS_BASE/build/lib/psmile -L$RNF_OASIS_BASE/build/lib/psmile/scrip -L$RNF_OASIS_BASE/build/lib/psmile/mct -L$RNF_OASIS_BASE/build/lib/psmile/mct/mpeu -lpsmile -lmct -lmpeu -lscrip"
export RNF_NETCDF_INCLUDE="-I$NETCDFROOT/include"
export RNF_NETCDF_LIB="-L$NETCDFROOT/lib -lnetcdf"
export RNF_NETCDFF_INCLUDE="-I$NETCDFFROOT/include"
export RNF_NETCDFF_LIB="-L$NETCDFFROOT/lib -lnetcdff"
export RNF_MPI_LIB="$MPI_LIB"
export RNF_FFLAGS="-r8 -fp-model precise -align array32byte -O3 -qopenmp -g -traceback -convert big_endian -march=core-avx2 -mtune=core-avx2"
export RNF_CFLAG="-fp-model precise -O3 -g -traceback -qopt-report=0 -fpe0 -qopenmp -march=core-avx2 -mtune=core-avx2"
export RNF_LFLAGS="$MPI_LIB -qopenmp"
export myfortrancompiler=$FC
export OASIS_ANCHOR=../../../oasis
export NETCDF_C_DIR=$NETCDFROOT
export NETCDF_F_DIR=$NETCDFFROOT
export OASIS_DIR=../../../oasis/arch_ecearth/
export USER=a270092
export ENVIRONMENT_SET_BY_ESMTOOLS=TRUE

unset SLURM_DISTRIBUTION
unset SLURM_NTASKS
unset SLURM_NPROCS
unset SLURM_ARBITRARY_NODELIST

pushd lpj_guess_raupach
mkdir -p build; cd build; cmake .. -DOASIS=ON -DCMAKE_BUILD_TYPE=Release; make -j8; cd ..
popd
